export default [
  { name: 'Cô tạo tình huống giao tiếp và hỗ trợ con thực hiện sau đó giảm dần hỗ trợ đến khi con tự thực hiện độc lập.' },
  { name: 'Con luyện phát âm thông qua hoạt động đọc thơ.' },
  { name: 'Cô làm mẫu phát âm đúng, sử dụng kỹ thuật PROMPT hỗ trợ, sau đó giảm dần hỗ trợ đến khi con có thể bắt chước phát âm đúng.                                                                                                                      ' },
  { name: 'Trong tình huống thực tế hằng ngày (chơi đồ chơi, đồ vật, …). Cô đưa ra yêu cầu/hỏi- đáp/ hỗ trợ/ chờ đợi con trả lời.' },
  { name: 'Trong các tình huống thực tế, con nhớ và truyền thông điệp/ gợi ý/ hỗ trợ con diễn đạt câu rõ ràng' },
  { name: 'Xem tranh ảnh con vật, chơi với mô hình đồ chơi con vật,...  Cô cung cấp vốn từ cho con sau đó cô sử dụng kỹ thuật Prompt hỗ trợ bật âm cho con.' },
  { name: 'Con cùng cô xem truyện tranh. Cô  kể mẫu, sau đó hướng dẫn con kể lại (có gợi nhắc để con tiếp tục)' },
  { name: 'Cô đưa ra câu hỏi gợi mở, chờ con trả lời, sau đó nhắc lại và mở rộng câu trả lời của con thành câu dài hơn' },
  { name: 'Con được luyện nói bằng cách hoàn thành câu bỏ lửng khi cô dừng lại (ví dụ: “Con mèo kêu …..meo… meo”).' },
  { name: 'Cô đưa ra 2 lựa chọn (VD: xe hay bóng) sau đó khuyến khích con trả lời bằng câu trọn vẹn thay vì chỉ chỉ tay' },
  { name: 'Trong giờ chơi, cô cố tình đặt đồ chơi xa tầm với để con phải dùng lời nói yêu cầu hoặc để đồ chơi vào hộp đậy kín để con yêu cầu mở.' },
  { name: 'Cô dùng tranh miêu tả hành động, gợi ý để con đặt câu “Bạn đang…” để con có thể mô tả/gọi tên hoạt động đang diễn ra (VD : ăn/uống…)' },
  { name: 'Khi chơi đóng vai cô hỗ trợ con dùng câu thoại ngắn, sau đó mở rộng dần' },
  { name: 'Con tập kể lại chuỗi tranh 3–4 bước, cô gợi ý từ khóa để con diễn đạt mạch lạc. ( VD : đầu tiên con kéo quần - sau đó con đi tè - tiếp theo con kéo quần lên - cuối cùng con rửa tay)' },
  { name: 'Con luyện nói nhắc lại các mẫu câu có cấu trúc (ví dụ: “Con muốn…”, “Con thích…”) khi chơi đồ chơi cùng cô/bạn để thể hiện nhu cầu' },
  { name: 'Cô dạy con sử dụng đại từ (con, mẹ, bạn, cô…) qua trò chơi đóng vai.' },
  { name: 'Con tập miêu tả đồ vật theo gợi ý đặc điểm: màu sắc, hình dáng, công dụng.' },
  { name: 'Cô chơi trò đoán đồ vật qua gợi ý: “Cái này tròn, màu vàng, ăn được” → con trả lời “Quả cam”' },
  { name: 'Cô khuyến khích con dùng từ nối (và, rồi, sau đó) để kể lại sự việc.' },
  { name: 'Cô dùng hình ảnh tình huống (VD: bé té ngã-bé khóc), yêu cầu con đặt câu miêu tả cảm xúc' },
  { name: 'Cô luyện cho con trả lời “tại sao” bằng câu đơn giản (VD: Con buồn-vì con đau chân”).' },
  { name: 'Con tập làm quen với câu có mệnh đề phụ: “Con muốn ăn bánh mà có nhân dâu' },
  { name: 'Cô dùng thẻ tranh động từ, yêu cầu con nói câu ở thì khác nhau (hôm qua – hôm nay – ngày mai)' },
]