export default [
    { name: 'Cô sử dụng trò chơi có thời gian ngắn (30 giây – 1 phút), yêu cầu con hoàn thành, sau đó tăng dần thời gian để rèn duy trì chú ý.' },
    { name: 'Hướng dẫn con thực hiện hoạt động, khi con sao nhãng, cô nhẹ nhàng gọi tên, hướng dẫn con quay lại hoạt động chính, củng cố khi con tập trung trở lại. Sử dụng phần thưởng tự thân để khích lệ con' },
    { name: 'Cô chia hoạt động lớn thành nhiều bước nhỏ, hỗ trợ con làm từng bước để tránh mất tập trung' },
    { name: 'Con tham gia trò chơi “nghe và lặp lại chuỗi từ/câu ngắn”, cô hỗ trợ và tăng dần độ dài để rèn ghi nhớ' },
    { name: 'Cô dùng đồng hồ cát/timer, yêu cầu con ngồi yên và tập trung làm việc trong khoảng thời gian cụ thể, sau đó nghỉ ngắn' },
    { name: 'Cô tổ chức trò chơi “nghe – làm theo”, yêu cầu con thực hiện 2–3 mệnh lệnh liên tiếp, giảm dần gợi ý để rèn trí nhớ làm việc' },
    { name: 'Cô hướng dẫn con thực hiện hoạt động, khi con quên, cô nhắc lại thông tin bằng câu ngắn, hình ảnh minh họa, hỗ trợ con ghi nhớ tốt hơn.' },
    { name: 'Cô sử dụng tranh dãy hoạt động (3–4 bước), yêu cầu con sắp xếp đúng thứ tự, hỗ trợ khi con quên hoặc xáo trộn' },
    { name: 'Con chơi trò “tìm đồ vật trong phòng”, cô mô tả gợi ý, hỗ trợ để con duy trì sự chú ý tìm kiếm đến khi hoàn thành.' },
    { name: 'Khi con khó ngồi yên, cô xen kẽ hoạt động vận động nhỏ (đứng lên – vỗ tay – ngồi xuống) để con giải tỏa năng lượng rồi quay lại chú ý.' },
    { name: 'Cô tạo trò chơi “nghe tiếng – phản ứng nhanh” (nghe trống → vỗ tay, nghe chuông → ngồi xuống) để rèn khả năng di chuyển chú ý' },
    { name: 'Con luyện trò “tìm điểm khác nhau” giữa hai bức tranh, cô hỗ trợ quan sát chi tiết, củng cố khi con duy trì tập trung đủ lâu' },
    { name: 'Cô cho con nghe 3–4 từ, yêu cầu con nhắc lại theo thứ tự, hỗ trợ ban đầu rồi giảm dần để rèn trí nhớ ngắn hạn.' },
    { name: 'Con chơi trò “ghép đôi thẻ”, cô hướng dẫn con nhớ vị trí thẻ đã mở, củng cố khi con ghi nhớ đúng.' },
    { name: 'Khi đọc truyện, cô dừng ở giữa, hỏi con “Có chuyện gì đã xảy ra?”, hỗ trợ để con nhớ lại chi tiết trước đó' },
    { name: 'Cô tổ chức trò chơi “đèn xanh – đèn đỏ”, yêu cầu con dừng/di chuyển đúng lúc để rèn khả năng chú ý – ức chế hành vi.' },
    { name: 'Con tham gia trò “làm theo nhịp” (cô vỗ tay 2 lần – con lặp lại; tăng dần số lần), để rèn ghi nhớ chuỗi động tác.' },
    { name: 'Khi con đang chú ý một hoạt động, cô đưa tín hiệu mới (âm thanh/đồ vật), hướng dẫn con chuyển sự chú ý từ việc cũ sang việc mới' },
    { name: 'Cô cho con quan sát một hình trong 1 phút, sau đó cất đi và hỏi con kể lại chi tiết, hỗ trợ ban đầu khi con nhanh quên.' },
]