export default [
    { name: 'Cô sử dụng những đồ chơi như: xe, con vật, hình khối, chơi lồng hộp… vui chơi trò chuyện, bình luận, cô làm mẫu hướng dẫn, hỏi đáp, củng cố' },
    { name: 'Sử dụng đồ dùng/ đồ chơi có trong phòng học. Cô tạo tình huống và hỗ trợ con thực hiện' },
    { name: 'Sử dụng đồ chơi (hộp đồ chơi hoa, bộ rau củ quả, khối gỗ…) có màu sắc nổi bật. Cô hướng dẫn/ làm mẫu/ hỗ trợ con thực hiện.' },
    { name: 'Cho con quan sát thẻ tranh/ mô hình về đồ vật/ con vật… Cô làm mẫu/ yêu cầu/ hỗ trợ con tìm đúng đối tượng' },
    { name: 'Cô đưa khối gỗ nhiều màu, yêu cầu con phân loại theo màu, cô hỗ trợ và củng cố' },
    { name: 'Cô cho con xếp hình đơn giản (xếp chồng 3–4 khối), làm mẫu, sau đó hỗ trợ con làm.' },
    { name: 'Cô sử dụng cặp thẻ giống nhau, yêu cầu con tìm và ghép đôi, hướng dẫn – hỗ trợ khi cần.' },
    { name: 'Cô tạo tình huống với bộ xếp hình, yêu cầu con ghép theo mẫu, cô làm mẫu rồi giảm dần gợi ý.' },
    { name: 'Cho con quan sát tranh có sự khác biệt nhỏ, cô hỏi “Có gì khác nhau?”, hỗ trợ con nhận biết.' },
    { name: 'Cô cho con chơi trò nối hình với bóng (tranh – bóng đen), hướng dẫn con tìm đúng.' },
    { name: 'Cô dùng hộp đồ chơi, giấu một món và yêu cầu con nhớ – tìm ra món đã mất.' },
    { name: 'Cô tạo trò chơi “xếp theo thứ tự” (to → nhỏ, thấp → cao), làm mẫu rồi khuyến khích con tự xếp.' },
    { name: 'Khi chơi ghép hình (puzzle), cô hướng dẫn con tìm mảnh khớp, hỗ trợ ban đầu rồi để con làm độc lập' },
    { name: 'Cô sử dụng thẻ tranh, hỏi con chọn đồ vật cùng nhóm (hoa quả – con vật – phương tiện), hỗ trợ củng cố.' },
    { name: 'Cô đưa đồ vật thật (cốc, thìa, bát…), yêu cầu con sắp theo công dụng, cô gợi ý và hỗ trợ' },
    { name: 'Cô cho con chơi trò “đoán đồ vật qua gợi ý” (tròn, màu đỏ, ăn được → quả táo), hỗ trợ con suy luận.' },
    { name: 'Cô tổ chức trò chơi nhớ tranh (xem 3 tranh → lật úp → hỏi con nhớ gì), cô hỗ trợ khi con quên' },
    { name: 'Cô cho con thực hành nối số lượng với tranh (3 quả bóng → số 3), cô làm mẫu – hỗ trợ.' },
    { name: 'Khi chơi lắp ghép lego, cô hướng dẫn con làm theo bước (chọn miếng đỏ, đặt lên miếng xanh), hỗ trợ củng cố.' },
    { name: 'Cô dùng tranh thứ tự hoạt động (rửa tay – ăn – đánh răng), yêu cầu con sắp xếp theo đúng trình tự' },
    { name: 'Cô dùng tranh thứ tự hoạt động (rửa tay – ăn – đánh răng), yêu cầu con sắp xếp theo đúng trình tự' },
    { name: 'Cô đưa các khối hình (vuông, tròn, tam giác), yêu cầu con phân biệt, cô làm mẫu và hỗ trợ.' },
    { name: 'Cô tạo tình huống chơi “đúng – sai” (ví dụ: đặt con cá lên cây), để con phát hiện và sửa, cô củng cố.' },
    { name: 'Cô cho con chơi trò tìm đường trong mê cung đơn giản, cô gợi ý và hỗ trợ khi con gặp khó khăn.' },
    { name: 'Cô dùng thẻ số 1–5, hướng dẫn con đếm đồ vật và ghép đúng số, cô hỗ trợ củng cố' },
    { name: 'Cô yêu cầu con chỉ và gọi tên đồ vật theo nhóm (hoa, con vật, quả…), cô hỗ trợ khi cần' },
    { name: 'Cô cho con chơi trò “trước – sau” bằng cách xếp hàng đồ chơi, cô làm mẫu và hướng dẫn con thực hiện.' },
    { name: 'Cô sử dụng tranh “tìm điểm giống-khác nhau” để con quan sát, cô gợi ý – hỗ trợ khi con chưa phát hiện.' },
]