export default [
    { name: 'Cô sử dụng tranh “tìm điểm giống-khác nhau” để con quan sát, cô gợi ý – hỗ trợ khi con chưa phát hiện.' },
    { name: 'Sử dụng bộ ghép hình có núm (phương tiện giao thông, hình khối...), cô hướng dẫn/ làm mẫu/ cầm tay hỗ trợ con thực hiện, giảm dần hỗ trợ đến khi con độc lập thực hiện.' },
    { name: 'Xúc bombo/ xúc đậu/…. cô làm mẫu sau đó hướng dẫn và hỗ trợ con thực hiện. Giảm dần hỗ trợ đến khi con thực hiện độc lập' },
    { name: 'Cô đưa kéo an toàn, làm mẫu cắt đường thẳng/đường cong, sau đó hỗ trợ con cắt' },
    { name: 'Con tập gấp giấy đơn giản, cô làm mẫu từng bước, hỗ trợ và giảm dần.' },
    { name: 'Cô cho con nặn đất sét, hướng dẫn cách lăn, bóp, vo tròn, sau đó con tự thực hiện' },
    { name: 'Cô cho con tô màu trong hình viền, hỗ trợ ban đầu, giảm dần để con tô độc lập' },
    { name: 'Cô dùng kẹp quần áo, hướng dẫn con mở–kẹp, sau đó con tự kẹp vào bảng' },
    { name: 'Con tập cài nút áo, kéo khóa, cô làm mẫu, hỗ trợ, giảm dần đến khi con tự làm được.' },
    { name: 'Cô cho con xếp chồng khối gỗ, hỗ trợ cân bằng, sau đó để con tự xếp.' },
    { name: 'Con tập mở–đóng nắp hộp, xoay nắp chai, cô làm mẫu, hướng dẫn và hỗ trợ.' },
    { name: 'Cô cho con dùng thìa xúc hạt từ bát này sang bát kia, hỗ trợ ban đầu, sau đó giảm dần.' },
    { name: 'Cô đưa bút chì màu, hướng dẫn con đồ theo nét chấm, giảm hỗ trợ để con tự đồ.' },
    { name: 'Con tập nối hình (chấm → chấm), cô làm mẫu và hướng dẫn con nối theo đường.' },
    { name: 'Cô cho con luyện vẽ các nét cơ bản (nét ngang, dọc, tròn), hỗ trợ tay khi cần, giảm dần hỗ trợ.' },
    { name: 'Con tập lắp các chi tiết lego đơn giản, cô hướng dẫn, sau đó con tự lắp' },
    { name: 'Cô cho con nhặt hạt nhỏ bằng nhíp, hướng dẫn cách cầm, hỗ trợ và giảm dần.' },
    { name: 'Con tập vẽ mặt cười, ngôi nhà, cô làm mẫu từng nét, hỗ trợ, sau đó để con tự vẽ.' },
    { name: 'Cô đưa tranh cắt rời, yêu cầu con dán đúng vị trí, hỗ trợ khi cần.' },
    { name: 'Cô cho con ghép que tính thành hình theo mẫu, hỗ trợ và củng cố khi con làm đúng.' },
    { name: 'Cô đưa trò chơi luồn dây qua lỗ, hướng dẫn cách xỏ, sau đó để con thực hiện độc lập.' },
]