export default [
    { name: 'Thông qua những hoạt động tại lớp, cô tạo tình huống sau đó hướng dẫn và hỗ trợ con thực hiện. Cô giảm dần hỗ trợ đến khi con độc lập thực hiện.' },
    { name: 'Thông qua các hoạt động thực tế, cô tạo tình huống, làm mẫu, gọi tên từ cốt lõi, hướng dẫn và hỗ trợ trẻ thực hiện' },
    { name: 'Các hoạt động vui chơi với con vật, sách có hình con vật…/Cô giới thiệu/ vui chơi/tạo cơ hội và chờ đợi để con có nhu cầu nói/hỗ trợ gọi tên từ cốt lõi/tập con bắt chước nói/thưởng.' },
    { name: 'Khi chơi đồ chơi, cô đưa ra yêu cầu đơn giản (“Lấy quả bóng”), hỗ trợ con làm theo, sau đó tăng dần độ khó.' },
    { name: 'Trong giờ chơi tương tác, cô yêu cầu con chọn theo lời nói (“Con lấy …), cô hỗ trợ và giảm dần gợi ý.' },
    { name: 'Cô chỉ vào tranh và nói tên, sau đó yêu cầu con chỉ theo yêu cầu (“Đâu là con mèo?”' },
    { name: 'Khi đọc sách tranh, cô mô tả nhân vật, yêu cầu con tìm đúng hình theo mô tả' },
    { name: 'Cô dùng tranh đối lập (to – nhỏ) yêu cầu con chọn đúng theo đặc điểm.' },
    { name: 'Cô dùng tranh đối lập (dài - ngắn) yêu cầu con chọn đúng theo đặc điểm' },
    { name: 'Cô giấu một món đồ, đưa gợi ý bằng lời, để con nghe hiểu và tìm ra vị trí cất giấu món đồ' },
    { name: 'Trong hoạt động phân loại, cô yêu cầu “Đặt quả táo vào rổ trái cây”, hỗ trợ con làm đúng' },
    { name: 'Cô luyện cho con hiểu câu phủ định (“Đừng lấy quả chuối, hãy lấy quả cam”' },
    { name: 'Trong trò chơi ghép tranh, cô mô tả chi tiết (“Tìm con vật màu vàng, biết gáy”), con chọn đúng hình' },
    { name: 'Khi kể chuyện, cô dừng lại hỏi “Ai đang làm gì?”, hỗ trợ con trả lời đúng nhân vật – hành động, VD : Thỏ con đang hái cà rốt' },
    { name: 'Cô đưa ra câu miêu tả có hai đặc điểm (“Chọn cái ghế màu đỏ, có tựa lưng”), để con hiểu và chọn đúng đồ cô đang miêu tả' },
    { name: 'Cô dạy con hiểu khái niệm vị trí (trên – dưới, trong – ngoài) bằng cách đặt đồ vật theo yêu cầu' },
    { name: 'Khi đi qua phòng khác chơi, cô chỉ hoạt động, gọi tên, sau đó hỏi “Con thấy cái gì?” để con phản hồi' },
    { name: 'Cô sử dụng lịch tranh (ăn, ngủ, chơi…), hỏi “Khi nào con đi học?” để con trả lời bằng cách chỉ hình.' },
    { name: 'Cô tạo tình huống vui nhộn (cố tình làm sai), để con hiểu và phản ứng bằng lời “sai rồi”, “không phải như vậy”' },
    { name: 'Khi xem 1 bức tranh hoặc video ngắn, cô dừng lại và hỏi “Chuyện gì đang xảy ra?”, hướng dẫn con trả lời.' },
    { name: 'Cô cho con nghe âm thanh (tiếng trống, tiếng xe), yêu cầu con chọn tranh/đồ vật đúng với âm thanh phát ra' },
    { name: 'Cô kể câu chuyện quen thuộc, sau đó hỏi lại chi tiết để con nhớ và trả lời.' },
    { name: 'Trong các hoạt động nhóm, cô cho con nghe yêu cầu chung và làm theo cùng các bạn' },
    { name: 'Cô dạy con hiểu câu hỏi “ở đâu” bằng cách giấu đồ vật rồi hỏi để con tìm đúng vị trí.' },
    { name: 'Cô hỗ trợ con hiểu khái niệm thời gian (hôm qua – hôm nay – ngày mai) qua lịch tranh và tình huống hằng ngày' },
]